require('config.lazy')
-- -- 键位
-- require('keymaps')
-- -- 基本设置
-- require('common')
-- -- 外观
-- require('appearance')
-- -- 必备
-- require('essential')
--
-- -- GUI编辑器
-- -- require('neovide')
-- -- 模糊查找
-- require('plugins.telescope')
-- -- 语言服务器
-- -- require('plugins.lspconfig')
