hwdec=auto
sub-bold=yes
profile=high-quality
video-sync=display-resample
interpolation

save-position-on-quit
sub-pos=95
sub-font-size=48

# 窗口整体缩放倍数（2K屏建议1.5–2.0，4K屏建议2.0–3.0）
window-scale=2.0
# 启用HiDPI窗口缩放（让界面元素也同步放大）
hidpi-window-scale=yes
# 窗口最大不超过屏幕的 90%×85%
autofit-larger=90%x85%
# 窗口最小不小于屏幕的 60%×60%
autofit-smaller=60%x60%
# 窗口居中（默认）
geometry=50%:50%
