# proxy settings
export http_proxy='http://localhost:12334'
export https_proxy=$http_proxy

# git credential manager
export GCM_CREDENTIAL_STORE=cache


## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[[ -f /home/yibo/.dart-cli-completion/zsh-config.zsh ]] && . /home/yibo/.dart-cli-completion/zsh-config.zsh || true
## [/Completion]

